config/routes.rb
Rails.application.routes.draw do

  # Old/bad URLs to send to /dev/null
  # TODO handle inside nginx or similar instead! Yeesh
  get '/temp.png', controller: 'home', action: 'discard', as: 'discard_temp_png'
  get '/data/temp.png', controller: 'home', action: 'discard', as: 'discard_data_temp_png'
  get '/tags/temp.png', controller: 'home', action: 'discard', as: 'discard_tags_temp_png'

  # Users/authentication via authlogic
  resources :users, only: [:index, :show] do
    resources :tags
  end
  resource  :user_session
  resources :password_reset
  get '/signup', controller: 'users', action: 'new', as: 'signup'
  get '/login', controller: 'user_sessions', action: 'new', as: 'login'
  get '/logout', controller: 'user_sessions', action: 'destroy', as: 'logout'
  get '/forgot_password', controller: 'password_reset', action: 'new', as: 'forgot_password'
  get '/settings', controller: 'users', action: 'edit', as: 'settings'
  patch '/settings', controller: 'users', action: 'update'
  put '/settings', controller: 'users', action: 'update'

  # Tags/data
  resources :tags, path: 'data' do
    resources :favorites, only: [:create]

    collection do
      get :latest
      get :random
    end

    member do
      post :thumbnail
      put :thumbnail
    end
  end
  post '/tags' => 'tags#create' # backwards-compatibility

  # TODO can these be inside the :tags resource declaration but maintain the /shorturls?
  get '/latest', controller: 'tags', action: 'latest', as: 'latest_tag'
  get '/random', controller: 'tags', action: 'random', as: 'random_tag'

  get  '/validator' => 'tags#validate', as: 'validator'
  post '/validate' => 'tags#validate', as: 'validate'

  # Apps
  resources :visualizations, path: 'apps' do
    member do
      put :approve
      put :unapprove
    end
  end

  # Favorites index (user's favorites list)
  resources :favorites, only: [:index]

  get '/activity' => 'home#activity', as: 'activity'

  get '/about' => 'home#about', as: 'about'

  root controller: 'home', action: 'index'
end

app/models/visualization.rb
class Visualization < ApplicationRecord

  # supported application types; stored as an Array to maintain order pre-ruby 1.9
  # possibly rename to 'language'? Not sure. Little distinction atm
  KINDS = [
      ['',''], #Other/misc
      ['Flash','flash'],
      ['Javascript','javascript'],
      ['C++','cpp'],
      ['openFrameworks (C++)','openframeworks'],
      ['Processing','processing'],
      ['Ruby','ruby'],
      ['Python','python'],
      ['Java','java'],
      ['Other','other'],
    ]

  belongs_to :user, optional: true
  belongs_to :approver, class_name: 'User', foreign_key: :approved_by, optional: true

  validates :user_id, presence: { message: "can't be blank" }, on: :create
  validates_associated :user, on: :create
  validates :name, presence: { message: "can't be blank (and should be cool)" }, uniqueness: { message: "must be unique & that name already exists" }, on: :create
  validates :description, presence: { message: "can't be blank, what is this supposed to do?" }, on: :create
  validates :authors, presence: { message: "can't be blank, put your username if nothing else" }, on: :create
  # validates :website, presence: { message: "can't be blank" }, on: :create
  validates :embed_url, presence: { message: "can't be blank" }, on: :create, if: :is_embeddable
  validate :reject_if_any_html


  scope :approved, -> { where('approved_at < ?', Time.now) }
  scope :pending, -> { where('approved_at IS NULL OR approved_at > ?', Time.now) }

  after_create :create_notification

  has_attached_file :image,
    default_style: :medium,
    # default_url: "/images/defaults/app_:style.jpg",
    default_url: "/images/defaults/app_:style.jpg",
    url: "/system/:class/:attachment/:id/:basename_:style.:extension",
    # path: ":rails_root/public/system/:class/:attachment/:id/:basename_:style.:extension",
    styles: { large: '600x600>', medium: "300x300>", small: '100x100#', tiny: "32x32#" }
  # validates_attachment_presence :image
  #TODO: remove :if conditionals; only needed with new version of Paperclip + Rails 2.3 (???); Weird bug.
	validates_attachment_content_type :image, content_type: ['image/jpeg', 'image/pjpeg', 'image/jpg', 'image/gif', 'image/png', 'image/x-png'], message: "Your thumbnail is not a valid image filetype (we accept JPG, PNG & GIF)", if: -> (e) { !e.image_file_name.blank? }
  validates_attachment_size :image, less_than: 1.megabyte, message: 'Your thumbnail must be less than 1 megabyte (MB).', if: -> (e) { !e.image_file_name.blank? }



  def approved?
    self.approved_at && self.approved_at < Time.now
  end

protected
  def create_notification
    Notification.create(subject: self, verb: 'created', user: self.user)
  end

  def reject_if_any_html
    self.attributes.each do |key,value|
      # Rails.logger.warn "Visualization field #{key} contains HTML: #{value} -- objects=#{self.inspect}"
      if value.present? && value.class == String && value.match(/href\=/)
        errors.add(key, "is invalid")
      end
    end
  end

end

app/controllers/visualizations_controller.rb
class VisualizationsController < ApplicationController

  before_action :get_visualization, only: [:show, :edit, :update, :destroy, :approve, :unapprove]
  before_action :require_admin, only: [:approve, :unapprove]
  before_action :require_owner, only: [:edit, :update, :destroy]
  before_action :require_user, only: [:new, :create]

  respond_to :html, :js, :xml, :json

  def show
    set_page_title @visualization.name
    respond_with @visualization do |format|
      format.html {}
      format.js
      format.xml
    end
  end

  def index
    set_page_title "GML Applications"
    current_objects
  end

  def new
    set_page_title "Creating new application"
    @visualization = Visualization.new
  end

  def create
    @visualization = current_user.visualizations.new(visualization_parameters)
    respond_with @visualization do |format|
      format.html do
        if @visualization.save
          flash[:notice] = "Application created"
          redirect_to visualization_path(@visualization)
        else
          flash[:error] = "Errors creating application"
          render :new
        end
      end
    end
  end

  def edit
    @visualization = Visualization.find(params[:id])
    set_page_title "Editing app #{@visualization.id}"
  end

  def update
    if @visualization.update(visualization_parameters)
      flash[:notice] = "Application updated"
      redirect_to visualization_path(@visualization)
    else
      flash[:error] = "Errors updating application"
      render :edit
    end
  end

  # Approve/reject an entry
  def approve
    update_approval_state(@visualization, true)
    flash[:notice] = "App was approved!"
    redirect_back_or_default(@visualization)
  end

  # DRY?
  def unapprove
    update_approval_state(@visualization, false)
    flash[:notice] = "App was unapproved"
    redirect_back_or_default(@visualization)
  end

protected

  def get_visualization
    @visualization = Visualization.find(params[:id])
  end

  def current_objects
    @page, @per_page = pagination_params
    which = is_admin? ? Visualization : Visualization.approved
    if params[:user_id]
      @user = User.find_by_param(params[:user_id])
      which = which.where(user_id: @user.id)
      #TODO: set page_title etc. Also handle all this logic less if/elsify
    end
    @visualizations ||= which.includes(:user).order('approved_at DESC, name ASC').paginate(page: @page, per_page: @per_page)
  end

  def update_approval_state(obj, enabled)
    logger.debug "hi from update_approval_state obj=#{obj.inspect}"
    obj.approved_at = (enabled ? Time.now : nil)
    obj.approved_by = (enabled ? current_user.id : nil)
    obj.save!
  end

  def require_owner
    raise NoPermissionError unless current_user && (@visualization.user == current_user || is_admin?)
  end

  private

  def visualization_parameters
    params.fetch(:visualization, {}).permit(:name, :description, :authors, :website, :embed_url, :kind, :is_embeddable, :image)
  end
end

app/views/visualizations/_form.html.haml
- required = '<span style="color: #d33">*</span>'
- visualization = @visualization || form

.right_column
  %p
    %label Submitter:
    %strong{style: 'margin-left: 3px;'}= link_to current_user.login
  %p
    %label{for: "visualization_authors"}== #{required.html_safe}Authors:
    = f.text_area :authors, rows: 2
  %p
    %label{for: "visualization_website"} Website:
    = f.text_field :website
  %p
    %label{for: "visualization_description"}== #{required.html_safe}Description:
    = f.text_area :description, rows: 6

  %p
    %label{for: 'visualization_image'}== Image/screenshot (JPG/PNG/GIF)
    = f.file_field :image, size: 10
  %p
    = image_tag(@visualization.image(:small))

.left_column
  %p
    %label{for: "visualization_name"}== #{required.html_safe}Name:
    = f.text_field :name
    %label{for: "visualization_version"} Version:
    = f.text_field :version, size: 5
  %p
    %label{for: "visualization_kind"}== #{required.html_safe}Kind:
    = f.select :kind, Visualization::KINDS

  %p.embed_toggle
    .left= f.check_box :is_embeddable, id: 'embeddable_toggle'
    %label{for: 'visualization_is_embeddable', style: 'margin-left: 1em', onclick: "$('#embeddable_toggle').click();"}== Embeddable?
  .embed_details{class: @visualization.is_embeddable ? '' : 'disabled'}
    %label{for: "visualization_embed_url"}== #{required.html_safe} URL to .swf, .js, etc
    = f.text_field :embed_url

    %label{for: "visualization_embed_callback"}== The name of a callback function, e.g. 'drawGML'
    = f.text_field :embed_callback

    %label{for: "visualization_embed_params"}==  Bonus parameters: foo=bar&bob=joe&...
    = f.text_field :embed_params

    %label{for: "visualization_embed_params"}==  Embed code (check the API docs)
    = f.text_area :embed_code, rows: 3

    %small
      %a{id: 'preview_embed', class: 'preview', onclick: "alert('TODO!');"} Preview




:javascript
  $(document).ready(function(){
    $('#embeddable_toggle').click(function(){
      var deets = $('.embed_details');
      // $(this).is(':checked')
      deets.find(':input').attr('disabled', !$(this).is(':checked'));
      if(deets.hasClass('disabled')){
        deets.removeClass('disabled');
        deets.find(':input').attr('disabled', false);
      }
      else {
        deets.addClass('disabled');
        deets.find(':input').attr('disabled', true);
      }
    });
  });

app/views/visualizations/edit.html.haml
%h1 Editing visualization

= render "layouts/error_messages", target: @visualization

= form_for(:visualization, url: visualization_url(@visualization), html: { method: :put, multipart: true }) do |f|
  = render partial: "form", locals: {f: f}
  %p.buttons= submit_tag "Update"

- if false
  = link_to 'Show', visualization_path(@visualization)
  |
  = link_to 'Back', visualizations_path

app/views/visualizations/index.html.haml
%p.create_new
  = link_to '+ Register New Application', new_visualization_path, class: 'button add facebox'

= pagination(@visualizations)

%table{style: 'width: 100%'}
  %tr
    / %th{style: 'width: 110px;'}
    %th{style: 'width: 100px;'} application
    %th{style: 'width: 200px;'}
    %th{style: 'width: 220px; padding: 0px 0px 0 25px;'} authors
    %th
    %th
    - if false
      %th{style: 'width: 40px;'} embeddable
      %th{style: 'width: 150px;'} submitted
    %th.controls
    - if is_admin? || is_owner?
      %th.admin{style: 'width: 40px;'}
      %th.admin{style: 'width: 80px;'}

  - @visualizations.each do |app|
    %tr.fat
      %td= link_to(image_tag(app.image(:small), width: 100), visualization_path(app))
      %td.name
        %strong= link_to app.name, visualization_path(app)
      %td.authors{style: 'line-height: 1.3em; padding: 0px 10px 0 15px;'}= app.authors[0..100] || '&mdash;'
      %td.language= app.kind.blank? ? '&mdash;' : app.kind
      %td.website{style: 'padding: 0px 5px 0 15px;'}= link_to (app.website&.gsub('http://','') || '&mdash;'), app.website
      - if false
        %td= app.is_embeddable? ? 'y' : 'n'
        %td{style: 'width: 20px; text-align: center; background-color: #f00;'}= link_to app.user.login, user_path(app.user) rescue "&mdash;"
        %td{style: 'width: 150px;'}= app.created_at.strftime('%D')
      %td.controls= link_to "more&nbsp;&raquo;".html_safe, visualization_path(app), class: 'ghost button'

      -#Admin debuggery & controls
      - if is_admin?
        %td.admin= app.approved? ? 'Approved' : 'Pending'
        %td.admin.controls
          - if app.approved?
            = link_to 'unapprove', unapprove_visualization_path(app), method: :put, confirm: 'Are you sure?'
          - else
            = link_to 'approve', approve_visualization_path(app), method: :put, confirm: 'Are you sure?'
          %br
          = link_to 'edit', edit_visualization_path(app)
          = link_to 'delete', visualization_path(app), method: :delete, confirm: "Are you sure?", class: 'delete'

%p= pagination(@visualizations)

=# render partial: 'visualization', collection: @visualizations

- if @visualizations.blank?
  %em None yet!

app/views/visualizations/new.html.haml
%h1 Register New Application

= render "layouts/error_messages", target: @visualization

= form_for(:visualization, url: visualizations_url, html: { multipart: true }) do |f|
  = render partial: "form", object: @visualization, locals: {f: f}
  %br
  %p= submit_tag "Create"

= link_to 'Back', visualizations_path

app/views/visualizations/show.html.haml
%p.back= link_to '&larr; back to applications'.html_safe, visualizations_path

.left{style: 'margin-top: 40px;'}
  = image_tag(@visualization.image(:medium))
  =# image_tag(@visualization.image(:large), width: 300)

.centered{style: 'width: 400px; margin: 20px 0 0 330px;'}
  %h1
    =h @visualization.name
    %span.version=h @visualization.version
  %div[@visualization]
    %p.authors
      %strong Author(s):
      =h @visualization.authors
    %p.website
      %strong Website:
      = link_to @visualization.website, "http://#{@visualization.website.gsub("http://",'')}"

    %hr
    - unless @visualization.kind.blank?
      %p
        %strong Language:
        =h Visualization::KINDS.select { |k,v| v == @visualization.kind }[0][0] rescue @visualization.kind
    - unless @visualization.download.blank?
      %p
        %strong Download:
        = link_to(@visualization.download, @visualization.download)

    .description
      %strong Description:
      = h @visualization.description || '(none)'

    - unless @visualization.user.nil?
      %hr
      %p
        %strong Submitted by:
        %span.user
          = link_to @visualization.user.login, user_path(@visualization.user)
        %span.submitted_at= @visualization.created_at.strftime('%D')


  - if logged_in? && (@visualization.respond_to?(:user) && @visualization.user == current_user) || is_admin?
    %hr
    %p.controls
      = link_to 'Edit', edit_visualization_path
      |
      = link_to 'Delete', visualization_path, confirm: 'Are you sure?', method: :delete

  - if is_admin?
    %p
      - if @visualization.approved?
        Approved by
        = link_to @visualization.approver.login, user_path(@visualization.approver)
        @
        = @visualization.approved_at
        = link_to 'Unapprove', unapprove_visualization_path, confirm: 'Are you sure?', method: :put
      - else
        Unapproved.
        = link_to 'Approve', approve_visualization_path, method: :put