config/routes.rb
Rails.application.routes.draw do

  # Old/bad URLs to send to /dev/null
  # TODO handle inside nginx or similar instead! Yeesh
  get '/temp.png', controller: 'home', action: 'discard', as: 'discard_temp_png'
  get '/data/temp.png', controller: 'home', action: 'discard', as: 'discard_data_temp_png'
  get '/tags/temp.png', controller: 'home', action: 'discard', as: 'discard_tags_temp_png'

  # Users/authentication via authlogic
  resources :users, only: [:index, :show] do
    resources :tags
  end
  resource  :user_session
  resources :password_reset
  get '/signup', controller: 'users', action: 'new', as: 'signup'
  get '/login', controller: 'user_sessions', action: 'new', as: 'login'
  get '/logout', controller: 'user_sessions', action: 'destroy', as: 'logout'
  get '/forgot_password', controller: 'password_reset', action: 'new', as: 'forgot_password'
  get '/settings', controller: 'users', action: 'edit', as: 'settings'
  patch '/settings', controller: 'users', action: 'update'
  put '/settings', controller: 'users', action: 'update'

  # Tags/data
  resources :tags, path: 'data' do
    resources :favorites, only: [:create]

    collection do
      get :latest
      get :random
    end

    member do
      post :thumbnail
      put :thumbnail
    end
  end
  post '/tags' => 'tags#create' # backwards-compatibility

  # TODO can these be inside the :tags resource declaration but maintain the /shorturls?
  get '/latest', controller: 'tags', action: 'latest', as: 'latest_tag'
  get '/random', controller: 'tags', action: 'random', as: 'random_tag'

  get  '/validator' => 'tags#validate', as: 'validator'
  post '/validate' => 'tags#validate', as: 'validate'

  # Apps
  resources :visualizations, path: 'apps' do
    member do
      put :approve
      put :unapprove
    end
  end

  # Favorites index (user's favorites list)
  resources :favorites, only: [:index]

  get '/activity' => 'home#activity', as: 'activity'

  get '/about' => 'home#about', as: 'about'

  root controller: 'home', action: 'index'
end

app/controllers/home_controller.rb
# frozen_string_literal: true

class HomeController < ApplicationController
  # caches_action :index, cache_path: 'home/index', expires_in: 30.minutes, if: :cache_request?

  def index
    @tags = Tag.order(created_at: :desc).limit(30).includes(:user)
    @tag = (@tags.present? && @tags[0]) || nil
    @prev = (@tags.present? && @tags[1]) || nil
    set_page_title('#000000book - an open database for Graffiti Markup Language (GML) files', suffix: false)
  end

  def activity
    @page, @per_page = pagination_params
    @notifications = Notification.paginate(page: @page, per_page: @per_page).order(id: :desc).includes(:subject)
    set_page_title 'Activity'
  end

  def about
    set_page_title 'About'
  end

  # Ghetto handling for known-bad URLs -- mapping them here as a blackhole
  def discard
    logger.warn 'Discarding request...'
    render nothing: true, status: :not_modified # Not Modified
  end
end

app/views/home/_notifications.html.haml
- notifications ||= @notifications
- if notifications.blank?
  = "None yet."
- else
  %table.notifications
    - notifications.each do |notif|
      - next if notif.nil? || notif.subject.nil?

      %tr
        %td.timeago
          = time_ago_in_words(notif.created_at).gsub('about ','')
          ago

        - begin
          - case notif.subject
          - when Tag
            - tag = notif.subject
            - user = tag.user
            %td.thumbnail= image_tag(tag.remote_image || tag.image.url(:small), height: '50', style: 'border: 1px solid #444')
            %td
              = link_to tag_title(tag), url_for(notif.subject)
              -# currently no user = API, and Tag should parse application name out of the GML
              -# so just displa that. In the future we will probably have both
              - if user.nil?
                == uploaded via API #{tag.application.blank? ? '' : "from #{application_link(tag.application)}"}
              - else
                == uploaded by #{link_to(user.login, user_path(user)) rescue '(niluser)'}
          - when User
            - user = notif.subject
            %td{colspan: 3}
              = link_to user.login, user_path(user)
              signed up
          - when Visualization
            %td{colspan: 3}
              - app = notif.subject
              = link_to notif.user.login, user_path(notif.user)
              submitted application
              = link_to app.name, visualization_path(app.name)
              == (#{app.kind})
          - when Favorite
            - fave = notif.subject
            - obj = fave.object
            -#FIXME assuming it's a Tag...
            - if obj.class == Tag
              %td.thumbnail= image_tag(obj.remote_image || obj.image.url(:small), height: '50', style: 'border: 1px solid #444')
            %td
              = link_to notif.user.login, user_path(notif.user)
              favorited
              = obj.class.to_s.downcase
              -#FIXME use tag_title -- make that part of Tag proper perhaps? hmm
              == #{link_to obj.title || "##{obj.id}", url_for(obj)}
          - else
            %td{colspan: 3}
              %em== No support for #{notif.subject.class.to_s} notification yet.
        - rescue
          == ERROR: #{$!}

app/views/home/about.html.erb
<div class="column_left" style="width: 650px;">

<%# TODO replace all these remote images with local ones %>
<%# even better, start using a CDN... %>

<p>
 <img src="http://fffff.at/fuckflickr/data/000000book/about-invert.png" alt="About" /><br>
 <b><i>The Library of Babel for graffiti blackbooks.</i></b><br>

 <img src="http://fffff.at/fuckflickr/data/000000book/web/000000book-handshake-invert.jpg" /><br>

<p>
	<object width="640" height="360"><param name="allowfullscreen" value="true" /><param name="allowscriptaccess" value="always" /><param name="movie" value="http://vimeo.com/moogaloop.swf?clip_id=8072358&amp;server=vimeo.com&amp;show_title=0&amp;show_byline=0&amp;show_portrait=0&amp;color=ffffff&amp;fullscreen=1" /><embed src="http://vimeo.com/moogaloop.swf?clip_id=8072358&amp;server=vimeo.com&amp;show_title=0&amp;show_byline=0&amp;show_portrait=0&amp;color=ffffff&amp;fullscreen=1" type="application/x-shockwave-flash" allowfullscreen="true" allowscriptaccess="always" width="640" height="360"></embed></object>
	<br/>
<p>
 <i><b>#000000</b>, -adjective<br>
 The hexadecimal representation of black, commonly used in mathematics and computer science.<br>

<p>
 <b>black book</b>, -noun<br>
 "A graffiti artist's sketchbook. Often used to sketch out and plan potential graffiti, and to collect tags from other writers."<br>
 ~ <a href="http://en.wikipedia.org/wiki/Graffiti_terminology">Wikipedia</a><br>
 </i>
 <br>

<p>
 <img src="http://fffff.at/fuckflickr/data/000000book/thumb/gml-file.png" /><br>

<p>
 #000000book is an open repository for sharing and archiving motion captured graffiti tags. Tags are saved as digital text files known as GML (Graffiti Markup Language), which can be captured through freely available software such as <a href="http://graffitianalysis.com">Graffiti Analyisis</a> (marker), <a href="http://graffitianalysis.com/iphone">DustTag</a> (iPhone), <a href="http://eyewrtier.org">EyeWriter</a> (eye movement) and <a href="http://graffitiresearchlab.com/?page_id=76">Laser Tag</a> (laser). Graffiti writers are invited to capture and share their own tags, and computer programmers are invited to create new applications and visualizations of the resulting data. The project aims to bring together two seemingly disparate communities that share an interest hacking systems, whether found in code or in the city.<br>
 <br>

<p>
 The GML & #000000book development team consists of <a href="http://jamiedubs.com/">Jamie Wilkinson</a>, <a href="http://evan-roth.com">Evan Roth</a>, <a href="http://www.theowatson.com/">Theodore Watson</a>, <a href="http://csugrue.com/">Chris Sugrue</a> and <a href="http://toddvanderlin.com/">Todd Vanderlin</a>; all members of the copyleft <a href="http://fffff.at">F.A.T. Lab</a>. Additional Flash development assistance from <a href="http://art.manorius.com/">Manolis Perrakis</a>.<br>

<p>
 Contact - info[at]000000book.com<br>

<p>
 For more technical information on 000000book please visit the <a href="http://jamiedubs.com/wikis/blackbook/">API/docs page</a>.
 <br>
<p>
 <img src="http://fffff.at/fuckflickr/data/000000book/grl-2-browser-diagram.png" width=911 />

<p><br />
 <a href="http://fffff.at"><img src="http://fffff.at/fuckflickr/data/FAT-LOGOS/thumb/FAT-2-invert.jpg" border=0 width=75 /></a>


</div>

app/views/home/activity.html.haml
%h2 Recent Database Activity
%p
  &larr;
  = link_to "back to home", root_path

= pagination(@notifications)
= render partial: 'notifications', object: @notifications #not :collection
%p= pagination(@notifications)

app/views/home/index.html.haml
-# RSS
= auto_discovery_link_tag(:rss, {format: :rss, controller: 'tags', action: 'index'}, title: '#0000book: Latest Tags')

-# Be a little more specific about what 'today' is.
- timezone = ActiveSupport::TimeZone["Pacific Time (US & Canada)"]
- today = DateTime.now.in_time_zone(timezone).to_date

#home

  #intro
    .right{style: 'font-weight: normal; margin-left: 20px; margin-top: 0px; color: #777;'}
      == #{pluralize Tag.where("created_at >= ?", today).count, 'tag'} uploaded
      == by #{pluralize Tag.where("created_at >= ?", today).select('DISTINCT gml_uniquekey').count, 'person'} today (last #{time_ago_in_words(today).gsub('about ','')})
      %br
      == &rarr; #{link_to 'view all activity', activity_path, style: 'text-decoration: underline;'}

    .welcome{style: 'width: 600px;'}
      %strong Welcome to #000000book
      == &ndash; read an #{link_to 'intro to GML', 'http://fffff.at/gml-week-graffiti-markup-language/'}
      == &ndash; uploading tags? #{link_to 'Register an account', signup_path}
      == <br/> Signup and #{link_to 'link your iPhone', settings_path} to claim your uploads

  #vanderplayer

    .prevnext
      - next_text = '&larr; next'.html_safe
      - prev_text = 'previous &rarr;'.html_safe
      %li= @next.nil? ? next_text : link_to(next_text, tag_path(@next), class: 'button')
      %li &nbsp;::&nbsp;
      %li= @prev.nil? ? prev_text : link_to(prev_text, tag_path(@prev), class: 'button')
    - if @tag.blank?
      %h2.warning Warning: no tag data
    - else
      %h2
        %a{href: tag_path(@tag)}= tag_title(@tag)
        %small
          - if true
            %span.application== &ndash; #{application_link(@tag.sexy_app_name)}
          - unless @tag.location.blank?
            %span.location== &ndash; #{@tag.location}
          - if !@tag.user.nil?
            %span.username== &ndash; #{link_to @tag.user.login, user_path(@tag.user)}
          - elsif @tag.secret_username.blank?
            %span.uniquekey== <em>&ndash;</em> #{secret_username_link(@tag.secret_username)}
          == &ndash; uploaded #{time_ago_in_words(@tag.created_at)} ago
      = render partial: 'tags/tag_playback', object: @tag

  - # List of tags
  #tag-list
    %ul#frontpage_tags
      - @tags.each do |tag|
        %li
          %span
            %a{href: tag_path(tag)}= tag_title(tag)
          %small
            -# unless tag.application.blank? && tag.gml_application.blank?
            - if true
              %span.application== <em>|</em> #{application_link(tag.sexy_app_name, short: true)}
            - if !tag.user.nil?
              %span.username== <em>|</em> #{link_to tag.user.login, user_path(tag.user)}
            - elsif !tag.secret_username.blank?
              %span.uniquekey== <em>|</em> #{secret_username_link(tag.secret_username)}
    %br
    %p.right
      %strong= link_to '<span>View all data &raquo;</span>'.html_safe, tags_path, class: 'button ghost small'