config/routes.rb
Rails.application.routes.draw do

  # Old/bad URLs to send to /dev/null
  # TODO handle inside nginx or similar instead! Yeesh
  get '/temp.png', controller: 'home', action: 'discard', as: 'discard_temp_png'
  get '/data/temp.png', controller: 'home', action: 'discard', as: 'discard_data_temp_png'
  get '/tags/temp.png', controller: 'home', action: 'discard', as: 'discard_tags_temp_png'

  # Users/authentication via authlogic
  resources :users, only: [:index, :show] do
    resources :tags
  end
  resource  :user_session
  resources :password_reset
  get '/signup', controller: 'users', action: 'new', as: 'signup'
  get '/login', controller: 'user_sessions', action: 'new', as: 'login'
  get '/logout', controller: 'user_sessions', action: 'destroy', as: 'logout'
  get '/forgot_password', controller: 'password_reset', action: 'new', as: 'forgot_password'
  get '/settings', controller: 'users', action: 'edit', as: 'settings'
  patch '/settings', controller: 'users', action: 'update'
  put '/settings', controller: 'users', action: 'update'

  # Tags/data
  resources :tags, path: 'data' do
    resources :favorites, only: [:create]

    collection do
      get :latest
      get :random
    end

    member do
      post :thumbnail
      put :thumbnail
    end
  end
  post '/tags' => 'tags#create' # backwards-compatibility

  # TODO can these be inside the :tags resource declaration but maintain the /shorturls?
  get '/latest', controller: 'tags', action: 'latest', as: 'latest_tag'
  get '/random', controller: 'tags', action: 'random', as: 'random_tag'

  get  '/validator' => 'tags#validate', as: 'validator'
  post '/validate' => 'tags#validate', as: 'validate'

  # Apps
  resources :visualizations, path: 'apps' do
    member do
      put :approve
      put :unapprove
    end
  end

  # Favorites index (user's favorites list)
  resources :favorites, only: [:index]

  get '/activity' => 'home#activity', as: 'activity'

  get '/about' => 'home#about', as: 'about'

  root controller: 'home', action: 'index'
end

app/controllers/tags_controller.rb
require 'ostruct'

class TagsController < ApplicationController

  # We allow open access to API #create -- no authentication or forgery protection
  protect_from_forgery except: [:show, :latest, :random, :create, :thumbnail, :validate]
  before_action :get_tag, only: [:show, :edit, :update, :destroy, :thumbnail]
  before_action :require_user, only: [:new, :edit, :update, :destroy]
  before_action :require_owner, only: [:edit, :update, :destroy]
  before_action :convert_app_id_to_app_name, only: [:update, :create]

  # Basic caching for :index?page=1 and :show actions
  after_action :expire_caches, only: [:update, :create, :destroy]
  # caches_action :index, expires_in: 30.minutes, if: :cache_request?
  # caches_action :show,  expires_in: 30.minutes, if: :cache_request?

  def index

    # Setup a search context for this tag: currently user or app
    if !params[:app].blank?
      @search_context = {key: :application, value: params[:app], conditions: ["application = ? OR gml_application = ?",params[:app],params[:app]] }
    elsif !params[:user].blank?
      # Specifically customized for the secret_username using gml_uniquekey_hash trailing 5 digits! breakable coupling!
      @search_context = {key: :user, value: params[:user], conditions: ["SUBSTRING(gml_uniquekey_hash, -5, 5) = ?", params[:user].gsub('anon-','')] }
    elsif !params[:location].blank?
      @search_context = {key: :location, value: params[:location], conditions: ["location LIKE ?", params[:location]] }
    elsif !params[:keywords].blank?
      @search_context = {key: :keywords, value: params[:keywords], conditions: ["gml_keywords LIKE ?", params[:keywords]]}
    elsif !params[:user_id].blank?
      @user = User.find_by_param(params[:user_id])
      raise ActiveRecord::RecordNotFound if @user.blank?
      @search_context = {key: :user, value: @user.login, conditions: ["user_id = ?",@user.id]}
    end

    # Check for invalid page parameter before sanitization
    if params[:page].present? && params[:page].to_i <= 0
      flash[:error] = "Invalid page number specified"
      redirect_to tags_path and return
    end

    @page, @per_page = pagination_params(per_page: 15)
    @tags ||= Tag.order('tags.created_at DESC').includes(:user).where(@search_context && @search_context[:conditions]).paginate(page: @page, per_page: @per_page)
    @applications ||= Tag.select("DISTINCT application AS name").order("name").where.not(application: [nil, ""]).map { |t| OpenStruct.new(name: t.name) }
    @applications.reject! { |app| app.name.blank? }

    set_page_title "GML Tags"+(@search_context ? ": #{@search_context[:key]}=#{@search_context[:value].inspect} " : '')

    # fresh_when last_modified: @tags.first.updated_at.utc unless @tags.blank?
    #, etag: @tags.first
    # expires_in 5.minutes, public: true unless logged_in? # Rack::Cache
    respond_to do |wants|
      wants.html { render 'index' }
      wants.xml  { render xml: @tags.to_xml(dasherize: false, except: Tag::HIDDEN_ATTRIBUTES, skip_types: true) }
      wants.json { render json: @tags.to_json(except: Tag::HIDDEN_ATTRIBUTES), callback: params[:callback], processingjs: params[:processingjs] }
      wants.rss  { render rss: @tags }
    end
  end

  def show
    set_page_title "Tag ##{@tag.id}"

    # We only need these instance variables when rendering HTML (aka ghetto interlok)
     if params[:format] == 'html' || params[:format] == nil
      @prev = Tag.where("id < ?", @tag.id).last
      @next = Tag.find_by("id > ?", @tag.id)

      @user = User.find_by_param(params[:user_id]) if params[:user_id]
      @user ||= @tag.user

      # Some ghetto 'excludes' stripping until Tag after_save cleanup is working 100%
      # FIXME wow. just wow.
      @tag.gml && @tag.gml.gsub!(/\<uniqueKey\>.*\<\/uniqueKey>/,'')
    end

    # Freak out if GML data is missing; this really isn't ever supposed to happen
    raise MissingDataError if @tag.gml.blank?

    # fresh_when last_modified: @tag.updated_at.utc, etag: @tag
    respond_to do |wants|
      wants.html  { render }
      wants.gml   { render xml: @tag.gml(iphone_rotate: params[:iphone_rotate]) }
      wants.xml   { render xml: @tag.to_xml(except: Tag::HIDDEN_ATTRIBUTES, dasherize: false, skip_types: true) }
      wants.json  {
        response['Access-Control-Allow-Origin'] = '*'
        response['Access-Control-Allow-Methods'] = 'GET, OPTIONS'
        response['Access-Control-Max-Age'] = '1728000'
        render json: @tag.to_json(except: Tag::HIDDEN_ATTRIBUTES), callback: params[:callback]
      }
    end
  end

  # Quick accessor to grab the latest tag -- great for running installations with the freshest GML
  # Hand off to :show except for HTML, which should redirect -- keep permalinks happy
  def latest
    @tag = Tag.order('created_at DESC').first
    redirect_to(tag_path(@tag), status: 302) and return if [nil,'html'].include?(params[:format])
    show
  end

  # Just a random tag -- redirect to canonical for HTML, but otherwise don't bother (API)
  def random
    require 'activerecord_random' # FIXME rails5 no longer autoloading the lib/ directory
    @tag = Tag.random
    redirect_to(tag_path(@tag), status: 302) and return if [nil,'html'].include?(params[:format])
    show
  end

  # Create/edit tags
  def new
    set_page_title 'Upload a Graffiti Markup Language (GML) file'
    @tag = Tag.new
  end

  def edit
    set_page_title "Editing Tag ##{@tag.id}"
    render action: 'new'
  end

  # Calls either create_from_form (on-site, more strict) or create_from_api (less strict)
  def create
    if params.blank?
      logger.warn "no params"
      raise "No params!"
    end

    if params[:check] == 'connected' #DustTag weirdness?
      logger.debug "connected check"
      head :ok
      return
    end

    if !params[:tag].blank? # sent by the form
      logger.debug "sent by the form"
      return create_from_form
    elsif !params[:gml].blank? # sent from an app!
      logger.debug "sent from an app"
      return create_from_api
    else
      # Otherwise error out, without displaying any sensitive or internal params
      error_text = "Error, could not create tag from your parameters: #{clean_params.inspect}"
      logger.warn error_text
      render plain: error_text, status: 422 #Unprocessable Entity
      return
    end

    expire_page(:index)
  end

  def update
    @tag.update(params[:tag].permit(:gml, :gml_file, :application, :description, :location, :image, :existing_application_id))
    if @tag.save
      flash[:notice] = "Tag ##{@tag.id} updated"
      redirect_to tag_path(@tag)
    else
      flash[:error] = "Could not update tag: #{$!}"
      render action: 'edit'
    end
  end

  def destroy
    @tag.destroy
    if @tag.destroy
      flash[:notice] = "Tag ##{@tag.id} destroyed"
    else
      flash[:error] = "Could not destroy tag: #{$!}"
    end
    # redirect_to(tags_path)
    redirect_back(fallback_location: root_path)
  end

  # Upload an image for a tag if one doesn't already exist (for GMLImageRenderer)
  def thumbnail
    if @tag.image.exists?
      render plain: 'thumbnail already exists', status: 409 and return
    end
    @tag.image = params[:image]
    @tag.save!
    render plain: "OK", status: 200, layout: false
  rescue
    logger.error $!
    render plain: "Error: #{$!}", status: 500
  end

  # Interactive GML Syntax Validator
  def validate
    if params[:id]
      @tag = Tag.find(params[:id])
    elsif params[:tag] && params[:tag][:id]
      @tag = Tag.find(params[:tag][:id])
    else
      @tag = Tag.new(params[:tag]&.permit(:gml, :gml_file, :application, :description, :location, :image, :existing_application_id) || {})
      @tag.gml = params[:gml] if @tag.gml.blank? && params[:gml]
    end
    @tag.validate_gml

    set_page_title "GML Syntax Validator"
    @noindex = true unless @tag.gml.blank?

    respond_to do |wants|
      wants.html {
        if request.xhr?
          render plain: @tag.validation_results.inspect
        else
          render 'validator'
        end
      }
      # FIXME to_xml does the fuckin' <hash> thing :(
      joined_hash = Hash[@tag.validation_results.map { |k,v| [k, v.join(";\n")] }]
      wants.xml   { render xml: joined_hash.to_xml(dasherize: false, skip_types: true) }
      wants.json  { render json: @tag.validation_results.to_json(callback: params[:callback]) }
      wants.xhr   { render plain: @tag.validation_results.map{|k,v| "#{k}=#{v.join(',') || 'none'}"}.join("\n") }
      wants.text  { render plain: @tag.validation_results.map{|k,v| "#{k}=#{v.join(',') || 'none'}"}.join("\n") }
    end
  end



protected

  def get_tag
    @tag = Tag.find(params[:id])
  end

  def require_owner
    logger.debug "require_owner (tag.id=#{@tag.id rescue nil}): current_user=#{current_user.id rescue nil}; tag.user.id=#{@tag.user.id rescue nil}"
    raise NoPermissionError unless current_user && @tag && (@tag.user == current_user || is_admin?)
  end

  # Create a tag uploaded w/o a user or authentication, via the ghetto-API
  # this is currently used for tempt from the Eyewriter, but will be expanded...
  def create_from_api
    # TODO add app uuid? or Hash app uuid?
    opts = {
      gml: params[:gml],
      ip: request.remote_ip,
      location: params[:location],
      application: params[:application],
      remote_secret: params[:secret],
      gml_uniquekey: params[:uniquekey],
      image: params[:image]
    }

    # Merge opts & params to let people attempt to add whatever...
    @tag = Tag.new(opts)
    if @tag.save
      if params[:redirect] && ['true','1'].include?(params[:redirect].to_s)
        redirect_to(@tag, status: 302) and return
      elsif !params[:redirect_back].blank? && !request.referer.blank?
        redirect_to(request.referer, allow_other_host: true) and return
      elsif !params[:redirect_to].blank?
        redirect_to(params[:redirect_to], allow_other_host: true) and return
      else
        render plain: @tag.id, status: 200 #OK
      end
    else

app/helpers/tags_helper.rb
# frozen_string_literal: true

module TagsHelper
  # default a title for a piece of data...
  def tag_title(tag)
    tag.title.presence || "##{tag.id}"
  end

  def tag_user_link(tag)
    if !tag.user.nil?
      link_to tag.user.login, user_path(tag.user), class: 'username_link'
    elsif tag.secret_username.present?
      secret_username_link(tag.secret_username)
    else
      'NULL'
    end
  end

  def secret_username_link(secret_username)
    link_to secret_username, tags_path(user: secret_username), class: 'username_link anon'
  end

  def application_link(app_name, _opts = {})
    return '[upload]' if app_name.blank?

    # Strip out the long-ass GA name...
    # shortname = (opts[:short] == true ? app_name.gsub('Graffiti Analysis ','GrafAnalysis') : app_name)
    shortname = app_name
    link_to shortname, tags_path(app: app_name), class: 'application_link anon'
  end

  def location_link(location, _opts = {})
    return 'NULL' if location.blank?

    link_to(location, tags_path(location: location), class: 'location_link')
  end

  # Builtin tag playback modes
  def tag_player(tag = nil, args = {})
    flash_tag_player(tag, args)
  end

  # Todd's flash player
  def flash_tag_player(tag = nil, args = {})
    # return '<br /><p><strong>[disabled in dev mode]</strong></p><br />' if dev? && !params[:flash]

    # No longer specifying a specific height, just width
    opts = { width: '100%', src: 'http://000000book.com/system/BlackBook.swf', bgcolor: '#000000' }.merge(args)

    # image_urls = tag.image.styles.keys.map { |s| ["image_#{s}", "http://#{request.host}:#{request.port}"+tag.image.url(s)] }.to_hash
    image_urls = { image_large: tag.image.url(:large) }
    flashvars = { gml_url: tag_url(tag, format: 'gml', iphone_rotate: (tag.from_iphone? ? '1' : nil)), embed: '&lt;embed&gt;TODOWHATUP&lt;/embed&gt;',
                  user: begin
                    tag.user.login
                  rescue StandardError
                    nil
                  end,
                  created_at: tag.created_at.to_s, created_date: tag.created_at.strftime('%D') }.merge(image_urls)

    public_attributes = %w[id application location user_id]
    flashvars.merge!(tag.attributes.slice(*public_attributes))

    querified_flashvars = flashvars.map { |k, v| "#{k}=#{CGI.escape(v.to_s) if v.present?}" }.join('&')
    embed = %(<embed src="#{opts[:src]}?#{querified_flashvars}" quality="high" scale="noscale" wmode="gpu" loop="true" bgcolor="#{opts[:bgcolor]}" width="#{opts[:width]}" name="BlackBook" align="middle" allowScriptAccess="always" allowFullScreen="true" type="application/x-shockwave-flash" pluginspage="http://www.adobe.com/go/getflashplayer" />)

    %(
      <object width="#{opts[:width]}">
        <param name="allowScriptAccess" value="always" />
        <param name="allowFullScreen" value="true" />
        <param name="quality" value="high" />
        <param name="scale" value="noscale" />
        <param name="wmode" value="gpu" />
        <param name="loop" value="true" />
        <param name="movie" value="#{opts[:src]}" />
        <param name="bgcolor" value="#{opts[:bgcolor]}" />
        #{flashvars.map { |key, value| "<param name=\"#{key}\" value=\"#{value}\" />\n\t\t\t\t" }}
        #{embed}
      </object>
    )
  end
end

app/views/tags/_canvas_player.html.erb
<% tag = canvas_player %>

<canvas id="canvas"></canvas>

<script src="/canvasplayer/processing.min.js" type="text/javascript" charset="utf-8"></script>
<script src="/canvasplayer/canvasplayer.js" type="text/javascript" charset="utf-8"></script>

<!-- load our GML via JSONp callback -->
<script type="text/javascript" charset="utf-8">
  var s = document.createElement('script');
  //s.setAttribute('src','http://000000book.com/data/'+tag_id+'.json?callback=load_gml');
  // var url = 'http://000000book.com/data/'+tag_id+'.json?callback=load_gml';
  var url = "<%= tag_path(@tag, :format => 'json', :callback => 'load_gml', iphone_rotate: 1) %>";
  // console.log("Loading GSON data from url: "+url);
  s.setAttribute('src', url);
  s.setAttribute('id','drawing_stuff');
  document.getElementsByTagName('body')[0].appendChild(s);
</script>

app/views/tags/_tag.html.haml
-# A single tag pls
-# link = @user ? user_tag_path(@user, tag) : tag_path(tag)
- link = tag_path(tag)

-# TODO FIXME lots of hardcoded styles/widths in here
.meta.right{style: 'position: absolute; width: 200px; margin: 10px 0 0 280px;'}
  %br
  %strong.title= link_to tag_title(tag), link
  .posted_at
    == #{time_ago_in_words(tag.created_at)} ago
    %br= tag.created_at.strftime('%D %T')
  - unless tag.sexy_app_name.blank?
    %p.application 
      %strong Application: <br />
      = application_link(h(tag.sexy_app_name)) || 'NULL'

  - if is_owner?(tag) && is_admin?
    .controls.left
      %small
        = link_to 'edit', edit_tag_path(tag)          
        &nbsp;
        = link_to 'delete', tag_path(tag), method: 'delete', class: 'delete', confirm: 'Are you sure?'
    
%p
  =# link_to image_tag(tag.image.url(:medium)), link
  -# if tag.image.exists?    
  - if tag.remote_image
    .image= link_to(image_tag(tag.thumbnail_image), link)
  - else
    .image= link_to(image_tag(tag.image(:medium), width: 260), link)

app/views/tags/_tag_playback.html.haml
- tag = tag_playback # FIXME

#main.tag.tabs

  %ul.tab_navigation
    %li= link_to 'HTML5', '#html5', class: 'selected'
    %li= link_to 'image', '#image'

  #html5
    %p= render partial: 'tags/canvas_player', object: @tag
    %span.beta== *note: html5 &lt;canvas&gt; player is beta; developers please check out the <a href="http://github.com/jamiew/canvasplayer">source code</a>

  #image
    - imgopts = {}
    - if @tag.image.exists?
      .image= image_tag @tag.image(:large), imgopts
    - elsif @tag.remote_image
      .image= image_tag @tag.remote_image, imgopts
    - else
      %h4.warning No thumbnail generated yet.

app/views/tags/index.html.haml
= auto_discovery_link_tag(:rss, params.merge({format: :rss}), title: page_title)

-# Some ghetto custom mastheads
- if @user
  .left
    = link_to "&larr; Back to user profile".html_safe, user_path(@user)
    %h3
      .left{style: 'margin-right: 8px; margin-top: 2px;'}
        = link_to image_tag(@user.photo(:tiny)), user_path(@user)
      == #{@user.login}'s #{@favorites ? 'favorites' : 'tags'} (#{@tags.total_entries})
    %br
- elsif @search_context
  .left
    = link_to '&larr; Back to all data'.html_safe, tags_path
    %h3
      Search:
      %span{style: 'font-weight: normal;'}== #{@search_context[:key]} = #{@search_context[:value]}

%p.create_new
  = link_to '+ Upload GML', new_tag_path, class: 'button facebox add'

- if @applications
  #app_nav
    %form{method: 'get', action: tags_path}
      %span filter by app:
      -# FIXME don't use params[] directly... dynamically use @search_context
      - param = CGI.unescape(params[:app]) rescue ''
      = select_tag :app, "<option></option>"+options_from_collection_for_select(@applications, "name", "name", param)
      = submit_tag 'search'

%p= pagination

%table{style: 'width: 100%'}
  %tr
    %th.thumbnail{style: 'width: 110px;'}
    %th.name name
    %th.application application
    %th.keywords keywords
    %th.who who
    %th.uploaded{style: 'width: 130px'} uploaded
    %th
  - if @tags.empty?
    %tr
      %td{colspan: 6}
        %h3 No results!

  - @tags.each do |tag|
    - user = tag.user
    -# url = user.nil? ? tag_path(tag) : user_tag_path(user,tag)
    - url = tag_path(tag)
    %tr
      %td.thumbnail
        - if Rails.env.development?
          n/a
        - else
          = link_to(image_tag(tag.thumbnail_image(:medium), width: 190), url)
      %td.name{style: 'padding-left: 10px;'}
        %strong= link_to(tag_title(tag), url)
      %td.application
        = application_link(tag.sexy_app_name)
      %td.keywords
        - if tag.gml_keywords.blank?
          &mdash;
        - else
          = tag.gml_keywords.split(',').map { |word| link_to word, tags_path(keywords: word) }.join(',').html_safe
      %td.who
        - if !user.nil?
          %a{href: user_path(user)}
            .user_photo.left{style: 'margin-top: -7px; padding-right: 5px;'}= image_tag(user.photo(:tiny))
            = user.login
        - elsif tag.secret_username
          = secret_username_link(tag.secret_username)
        - elsif false && tag.author
          = link_to tag.author
        - else
          &mdash;
      %td.timeago.uploaded
        %abbr{title: tag.created_at.strftime('%D %T')}== #{timeago(tag.created_at)} ago
      / Meta
      %td.center
        = link_to 'download GML', tag_path(tag, format: :gml), class: 'button smallbutton'
        - if is_admin? || is_owner?
          %br
          %p.controls.right
            = link_to 'edit', edit_tag_path(tag)
            = link_to 'delete', tag_path(tag), method: 'delete', class: 'delete', confirm: 'Are you sure?'

%p= pagination

app/views/tags/show.html.haml
/ Top level navigation
- all_link = @user ? user_tags_path(@user) : tags_path
/ .floatLeft= link_to '&larr; back'.html_safe, all_link
.prevnext
  - prev_text = '&larr; next'.html_safe
  %li= @next.nil? ? prev_text : link_to(prev_text, tag_path(@next), class: 'button')
  %li &nbsp;::&nbsp;
  - next_text = 'previous &rarr;'.html_safe
  %li= @prev.nil? ? next_text : link_to(next_text, tag_path(@prev), class: 'button')
  %br.clear


#sidebar.tag_sidebar
  / Information about the tag
  .metadata.infobox
    - if true # show for logged-out users as well, to encourage logging in
      .right.favorite
        - on = current_user && @tag.favorited_by?(current_user) || false
        = link_to 'Favorite', tag_favorites_path(@tag), method: 'post', class: "favorite button #{on ? 'on' : 'off'}"
    %h2= tag_title(@tag)
    %hr
    %ul
      %li
        == Uploaded #{@tag.created_at.strftime("%D %T")}
        %br== (#{time_ago_in_words(@tag.created_at)} ago)
    %hr
    %ul
      - app = !@tag.gml_application.blank? && @tag.gml_application || @tag.application
      %li== <strong>Application:</strong> #{app.blank? ? 'NULL' : application_link(h(@tag.sexy_app_name))}
      %li== <strong>Keywords:</strong> #{@tag.gml_keywords.blank? ? 'NULL' : h(@tag.gml_keywords)}
    %hr
    %ul
      - if !@tag.author.blank?
        %li== <strong>Author:</strong> #{@tag.author}
      %li== <strong>Uploader:</strong> #{@user.blank? ? (@tag.secret_username.blank? ? 'NULL' : secret_username_link(@tag.secret_username)) : link_to(@user.login, user_path(@user)) }
      %li== <strong>Location:</strong> #{@tag.location.blank? ? 'NULL' : h(@tag.location)}
      - unless @tag.description.blank?
        %li== <strong>Description:</strong> #{h(@tag.description)}
      - if @tag.image.exists? || @tag.remote_image
        - url = (@tag.image.exists? ? @tag.image.url(:original) : @tag.remote_image)
        - #Quick little gsub to remove the queryvars... not ideal
        %li== Image: #{link_to(File.basename(url.gsub(/\?.*/,'')), url, target: '_blank') }


    %hr
    %br
    =# link_to '<small>Validate GML</small>'.html_safe, validate_tag_path(@tag), class: 'button', rel: 'nofollow'

    .gml
      %span.download= link_to('download GML', tag_path(@tag, format: :gml), class: 'button smallbutton')
      %span.what-is-gml= link_to('?', 'http://fffff.at/gml-week-graffiti-markup-language/', target: '_blank')
      %textarea.gml{cols: 24, rows: 12, onclick: '$(this).select();'}= @tag.gml

  -# Tag modbox -- edit/delete/debugging etc.
  - if is_owner?(@tag) || is_admin?
    .modbox.infobox
      %h2{style: 'color: #f0f'} MODBOX
      %ol#controls
        %li= link_to '<strong>edit</strong>', edit_tag_path, class: ''
        %li= link_to 'delete', tag_path, method: 'delete', class: 'delete', style: 'color: #fbb'
      %p
        %strong{style: 'color: #f0f'} Secret Fields
        - ['gml_uniquekey', 'gml_uniquekey_hash'].each do |field|
          %p{style: 'overflow: hidden;'}
            %strong= field
            %br
            %input{type: 'text', readonly: 'readonly', value: @tag.attributes[field], onclick: '$(this).select();'}
      %p
        %strong{style: 'color: #f0f'} Parsed GML Header
        - @tag.gml_header.each do |k,v|
          %p{style: 'overflow: hidden;'}
            %strong= k
            %br
            %span=h !v.blank? && v || 'NULL'

/ The actual tag awwwwwww yeah
= render partial: "tags/tag_playback", object: @tag

app/views/tags/validator.html.haml
- required = redstar

#validator.full.centered
  - if false
    %p= link_to '&larr; back to all tags', tags_path
  %p &nbsp;
  #form
    = form_for(@tag, url: validate_path, method: :post) do |form|
      .floatLeft= form.label :id, '000000book Tag ID:'
      &nbsp;&nbsp;
      = form.text_field :id, size: 5
      = form.submit 'Validate'

      .spacer{style: 'display: block; margin: 10px 50px 20px; font-style: italic;'} or

      = form.label :gml_file, 'Upload <abbr>GML</abbr> file:'.html_safe
      = form.file_field :gml_file, size: 10
      = form.submit 'Validate'

      .spacer{style: 'display: block; margin: 10px 50px 20px; font-style: italic;'} or

      = form.label :gml, 'Raw GML:'
      = form.label :gml, "paste raw GML #{required}".html_safe
      = form.text_area :gml, rows: 14
      %p= form.submit 'Validate'

  - if @tag.gml.blank?
    %h1 GML Syntax Validator

    == Upload or paste in your Graffiti Markup Language to test it out.
    %p== Check out the #{link_to 'reference GML spec', 'http://graffitimarkuplanguage.com/spec'}

    %h3 What does this do?
    %ul.square
      %li Check for syntax errors
      %li Are you missing any important tags?
      %li Make sure other GML players will be able to scale & orient correctly
      %li Ensure maximum awesome

    %br
    %h3 Protips
    == #{redstar} every GML tag page on 000000book now has a "#{(link_to('Validate GML', validate_tag_path(Tag.last)) rescue 'Validate GML')}" link to jump here quickly.
    %p== #{redstar} API-enabled: POST to this page with your data in the "gml" or "tag[gml]" field, or after uploading try fetching URLs like:
    %ul.formats.square
      - reference_tag = 161 # A personal favorite
      %li= link_to validate_tag_url(id: reference_tag, format: "xml"), validate_tag_url(id: reference_tag, format: "xml")
      %li= link_to validate_tag_url(id: reference_tag, format: "json"), validate_tag_url(id: reference_tag, format: "json")
      / %li= link_to validate_tag_url(id: reference_tag, format: "txt"), validate_tag_url(id: reference_tag, format: "txt")
  - else
    #results
      - if @tag.new_record?
        %h1= 'Validating Your Uploaded GML...'
      - else
        %h1== Validating Tag ##{@tag.id}...

      - if @tag.validation_results.values.flatten.blank?
        .congratulations
          Congratulations! Your GML is valid!
          = image_tag('applause.gif')
      - else
        %dl
          - @tag.validation_results.each do |key,values|
            %dt{class: key}== #{pluralize values.length, key.to_s.singularize}
            %dd{class: key}
              %ul
                - values.each do |value|
                  %li=h value