config/routes.rb
Rails.application.routes.draw do

  # Old/bad URLs to send to /dev/null
  # TODO handle inside nginx or similar instead! Yeesh
  get '/temp.png', controller: 'home', action: 'discard', as: 'discard_temp_png'
  get '/data/temp.png', controller: 'home', action: 'discard', as: 'discard_data_temp_png'
  get '/tags/temp.png', controller: 'home', action: 'discard', as: 'discard_tags_temp_png'

  # Users/authentication via authlogic
  resources :users, only: [:index, :show] do
    resources :tags
  end
  resource  :user_session
  resources :password_reset
  get '/signup', controller: 'users', action: 'new', as: 'signup'
  get '/login', controller: 'user_sessions', action: 'new', as: 'login'
  get '/logout', controller: 'user_sessions', action: 'destroy', as: 'logout'
  get '/forgot_password', controller: 'password_reset', action: 'new', as: 'forgot_password'
  get '/settings', controller: 'users', action: 'edit', as: 'settings'
  patch '/settings', controller: 'users', action: 'update'
  put '/settings', controller: 'users', action: 'update'

  # Tags/data
  resources :tags, path: 'data' do
    resources :favorites, only: [:create]

    collection do
      get :latest
      get :random
    end

    member do
      post :thumbnail
      put :thumbnail
    end
  end
  post '/tags' => 'tags#create' # backwards-compatibility

  # TODO can these be inside the :tags resource declaration but maintain the /shorturls?
  get '/latest', controller: 'tags', action: 'latest', as: 'latest_tag'
  get '/random', controller: 'tags', action: 'random', as: 'random_tag'

  get  '/validator' => 'tags#validate', as: 'validator'
  post '/validate' => 'tags#validate', as: 'validate'

  # Apps
  resources :visualizations, path: 'apps' do
    member do
      put :approve
      put :unapprove
    end
  end

  # Favorites index (user's favorites list)
  resources :favorites, only: [:index]

  get '/activity' => 'home#activity', as: 'activity'

  get '/about' => 'home#about', as: 'about'

  root controller: 'home', action: 'index'
end

app/views/layouts/_error_messages.html.erb
<% if target.errors.any? %>
<div class="error_explanation">
  <h2>
  	<%= pluralize(target.errors.count, "error") %> prevented this record from being saved:
  </h2>
  <ul>
  <% target.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
  <% end %>
  </ul>
</div>
<% end %>

app/views/layouts/_footer.html.haml
%br{style: 'clear: both;'}

#footer
  - spacer = "&nbsp;/&nbsp;".html_safe
  = link_to 'about', '/about'
  = spacer
  %script{type: 'text/javascript'} document.write('<a href="mailto:info@000000book.com">contact</a>');
  = spacer
  = link_to 'system activity', activity_path
  = spacer
  = link_to 'source code', 'http://github.com/jamiew/blackbook', target: '_blank'
  = spacer

  == powered by #{link_to 'FAT Lab', 'http://fffff.at'}
  &mdash;
  == copyfree 2009-#{Date.today.year}

app/views/layouts/_header.html.haml
-# Common code we're using on every page (for the time being)
#header
  %ul.navigation.user_navigation
    = yield :header_nav
  %ul.navigation.buttons
    -#TODO: select the currently active link
    %li= link_to 'data', tags_path
    %li= link_to 'applications', visualizations_path
    %li= link_to 'API/docs', "https://github.com/jamiew/blackbook/wiki/", target: '_blank'
    %li= link_to 'about', "/about"
    - if false
      %li= link_to 'activity', activity_path
  .masthead
    - if false
      %h1.title= link_to '#000000book', root_path, class: 'root_link'
      %h2.byline= link_to "An open database for Graffiti Markup Language (GML) files", root_path, class: 'root_link'
    - alt = '#000000book: An open database for Graffiti Markup Language (GML) files'
    %h1
      %a.root_link{href: root_path}
        = image_tag("/images/000000book-logo-beta.png", alt: alt, title: alt)

app/views/layouts/_stats.html.erb
<!-- Google Analytics -->
<script type="text/javascript">
var gaJsHost = (("https:" == document.location.protocol) ? "https://ssl." : "http://www.");
document.write(unescape("%3Cscript src='" + gaJsHost + "google-analytics.com/ga.js' type='text/javascript'%3E%3C/script%3E"));
</script>
<script type="text/javascript">
try {
var pageTracker = _gat._getTracker("UA-96220-19");
pageTracker._trackPageview();
} catch(err) {}</script>

app/views/layouts/_template_header.html.haml
%head
  %meta{ http_equiv_attrs }
  %meta{ 'http-equiv' => 'imagetoolbar', content: 'no' }
  %meta{ name: 'distribution', content: 'all' }
  %meta{ name: 'robots', content: @noindex ? 'noindex,follow' : 'all' }
  %meta{ name: 'resource-type', content: 'document' }
  %meta{ name: 'MSSmartTagsPreventParsing', content: 'true' }

  = stylesheet_link_tag 'application', media: 'all', 'data-turbo-track' => 'reload'
  = javascript_include_tag 'application', 'data-turbo-track' => 'reload'
  = csrf_meta_tags

  = yield :head

  %title= page_title

app/views/layouts/application.html.haml
- content_for :header_nav do
  - if current_user
    %li.user_photo= link_to image_tag(current_user.photo.url(:tiny), class: 'photo'), user_path(current_user)
    -# %li.user_name= link_to current_user.login, user_path(current_user)
    %li= link_to 'settings', settings_path
    -# %li= link_to 'favorites', favorites_path
    %li.logout= link_to 'logout', logout_path, class: 'logout'
  - else
    %li= link_to 'login', login_path
    %li= link_to 'signup', signup_path

!!!
%html{html_attrs}
  = render partial: 'layouts/template_header'
  %body
    #container
      = render partial: 'layouts/header'
      #content
        = flash_messages.present? && flash_messages.map(&:to_s).join.html_safe || ''
        = yield :layout
      = render partial: 'layouts/footer'

  - if Rails.env == 'production'
    = render partial: 'layouts/stats'